import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../global.css";

import { connectToMongoDB } from "@/lib/db";
import { Providers } from "../Providers/Provider";

import { Box } from "@chakra-ui/react";
import Header from "@/component/Header/Header";
import AdminSideBar from "@/component/AdminSideBar/AdminSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin OHIF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectToMongoDB();
  return (
    <Box >
      <AdminSideBar>{children}</AdminSideBar>
    </Box>
  );
}
