// app/layout.tsx (or app/layout.js if using JavaScript)

import './globals.css';
import ClientOnly from './components/ClientOnly/ClientOnly';
import getCurrentUser from './actions/getCurrentUser';

export const metadata = {
  title: 'Grantaly',
  description: 'Generated by create next app',
};

export const dynamic = "force-dynamic"

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // You can perform server-side data fetching here if needed
  // For example, you could fetch user data or any other required data

  // Simulating a data fetch (replace this with actual data fetching logic)
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <ClientOnly user={user}>
           {children}
        </ClientOnly>
      </body>
    </html>
  );
}
