// app/layout.tsx (or app/layout.js if using JavaScript)

import './globals.css';
import ClientOnly from './components/ClientOnly/ClientOnly';

export const metadata = {
  title: 'Grantaly',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // You can perform server-side data fetching here if needed
  // For example, you could fetch user data or any other required data

  // Simulating a data fetch (replace this with actual data fetching logic)
  const data = await fetchData();

  return (
    <html lang="en">
      <body>
        <ClientOnly>
           {children}
        </ClientOnly>
      </body>
    </html>
  );
}

async function fetchData() {
  // return new Promise((resolve) => {
  //   setTimeout(() => {
  //     resolve({ someData: 'This is some server-side data' });
  //   }, 1000);
  // });

  //  If need anything from server side either by actions or create actions here
}
